name: kpi_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  http: ^1.2.2
  get_it: ^7.7.0
  injectable: ^2.4.2
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

dev_dependencies:
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true